# Generated by Django 4.2.10 on 2024-02-08 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField(max_length=20, verbose_name='Широта')),
                ('longitude', models.FloatField(max_length=20, verbose_name='Долгота')),
                ('height', models.IntegerField(verbose_name='Высота')),
            ],
            options={
                'verbose_name': 'Координату',
                'verbose_name_plural': 'Координаты',
            },
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summer', models.CharField(choices=[('1A', '1A'), ('1B', '1B'), ('1C', '1C'), ('2A', '2A'), ('2B', '2B'), ('2C', '2C'), ('3A', '3A'), ('3B', '3B'), ('3C', '3C')], max_length=2, verbose_name='Лето')),
                ('autumn', models.CharField(choices=[('1A', '1A'), ('1B', '1B'), ('1C', '1C'), ('2A', '2A'), ('2B', '2B'), ('2C', '2C'), ('3A', '3A'), ('3B', '3B'), ('3C', '3C')], max_length=2, verbose_name='Осень')),
                ('winter', models.CharField(choices=[('1A', '1A'), ('1B', '1B'), ('1C', '1C'), ('2A', '2A'), ('2B', '2B'), ('2C', '2C'), ('3A', '3A'), ('3B', '3B'), ('3C', '3C')], max_length=2, verbose_name='Зима')),
                ('spring', models.CharField(choices=[('1A', '1A'), ('1B', '1B'), ('1C', '1C'), ('2A', '2A'), ('2B', '2B'), ('2C', '2C'), ('3A', '3A'), ('3B', '3B'), ('3C', '3C')], max_length=2, verbose_name='Весна')),
            ],
            options={
                'verbose_name': 'Уровень сложности',
                'verbose_name_plural': 'Уровни сложности',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fam', models.CharField(max_length=128, verbose_name='Фамилия')),
                ('name', models.CharField(max_length=128, verbose_name='Имя')),
                ('otc', models.CharField(max_length=128, verbose_name='Отчество')),
                ('email', models.EmailField(max_length=128)),
                ('phone', models.IntegerField(verbose_name='Телефон')),
            ],
            options={
                'verbose_name': 'Пользователя',
                'verbose_name_plural': 'Пользователи',
            },
        ),
        migrations.CreateModel(
            name='Perevals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beauty_title', models.CharField(max_length=200, verbose_name='Полное название перевала')),
                ('title', models.CharField(max_length=200, verbose_name='Название участка перевала')),
                ('other_titles', models.CharField(max_length=200, verbose_name='Допольнительно')),
                ('connect', models.CharField(max_length=200, verbose_name='Соединяется с')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('status', models.CharField(choices=[('new', 'Создано'), ('pending', 'Взято в модерацию'), ('accepted', 'Принято'), ('rejected', 'Отклонено')], default='new', max_length=10, verbose_name='Статус заявки')),
                ('coord', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='database.coords', verbose_name='Координаты')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.level', verbose_name='Уровень сложности')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.users', verbose_name='Турист')),
            ],
            options={
                'verbose_name': 'Перевал',
                'verbose_name_plural': 'Перевалы',
            },
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название изображения')),
                ('date_added', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата добавления')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Изображение')),
                ('pereval', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.perevals', verbose_name='Перевал')),
            ],
            options={
                'verbose_name': 'Изображение',
                'verbose_name_plural': 'Изображения',
            },
        ),
    ]
